#cloud-config
users:
  - name: core
    coreos-ssh-import-github-users:
      - 90kts
    groups:
      - sudo
      - docker
      - systemd-journal
write_files:
  - path: /etc/motd.d/flud.conf
    owner: root:root
    content: |

      ---
      Flooded.IO: A Load Testing Endpoint
      ---

  - path: /etc/profile.d/aliases.sh
    content: |
      alias f=fleetctl
      alias e=etcdctl
      alias s=systemctl
      alias j=journalctl
      alias d=docker

  - path: /home/core/conf.d/nginx.yaml
    content: |
      init_config:

      instances:
          -   nginx_status_url: http://0.0.0.0:8008/status/
              tags:
                  -   instance:loadtest

coreos:
  update:
    reboot-strategy: off
  units:
    - name: etcd2.service
      command: stop
    - name: fleet.service
      command: stop
    - name: datadog.service
      command: start
      content: |
        [Unit]
        Description=dd-agent
        Requires=docker.service
        [Service]
        User=core
        TimeoutStartSec=0
        Restart=always
        ExecStartPre=-/usr/bin/docker kill dd-agent
        ExecStartPre=-/usr/bin/docker rm dd-agent
        ExecStartPre=-/usr/bin/docker pull datadog/docker-dd-agent:latest
        ExecStart=/usr/bin/docker run --name dd-agent --net=host -v /home/core/conf.d:/conf.d:ro -v /var/run/docker.sock:/var/run/docker.sock -v /proc/:/host/proc/:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e API_KEY=DD_API_KEY datadog/docker-dd-agent:latest
        ExecStop=/usr/bin/docker stop dd-agent
    - name: loadtest.service
      command: start
      content: |
        [Unit]
        Description=flooded.io
        After=docker.service
        [Service]
        User=core
        TimeoutStartSec=0
        Restart=always
        ExecStartPre=-/usr/bin/docker kill loadtest
        ExecStartPre=-/usr/bin/docker rm loadtest
        ExecStartPre=/usr/bin/docker pull floodio/loadtest
        ExecStart=/usr/bin/docker run --name loadtest --log-driver=none --net=host floodio/loadtest
        ExecStop=/usr/bin/docker stop loadtest
