apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: timkoopmansloadtest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: timkoopmansloadtest 
    spec:
      containers:
        - name: timkoopmansloadtest 
          image: floodcontainerregistry.azurecr.io/timkoopmansloadtest
          ports:
          - containerPort: 8008